## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

In [2]:
#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [3]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [4]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df.head(10)

Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development
5        No  Research & Development
6        No  Research & Development
7        No  Research & Development
8        No  Research & Development
9        No  Research & Development

In [5]:
# Create a list of at least 10 column names to use as X data
selected_columns = [
    'Age', 
    'DistanceFromHome', 
    'Education', 
    'EnvironmentSatisfaction',
    'HourlyRate', 
    'JobInvolvement', 
    'JobLevel', 
    'JobSatisfaction',
    'NumCompaniesWorked',
    'PercentSalaryHike',
    'OverTime', 
    'YearsAtCompany',
    'TotalWorkingYears', 
    'YearsAtCompany', 
    'YearsInCurrentRole', 
    'YearsSinceLastPromotion', 
    'YearsWithCurrManager' 
    ]


# Create X_df using your selected columns
X_df = attrition_df[selected_columns]


In [6]:
# Show the data types for X_df
X_df.dtypes

Age                         int64
DistanceFromHome            int64
Education                   int64
EnvironmentSatisfaction     int64
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobSatisfaction             int64
NumCompaniesWorked          int64
PercentSalaryHike           int64
OverTime                   object
YearsAtCompany              int64
TotalWorkingYears           int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [7]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)


In [8]:
# Check values for OverTime
print(X_train["OverTime"].unique())

['No' 'Yes']


In [9]:
# Map 'OverTime' column values from 'Yes'/'No' to 1/0 in the training and testing sets

X_train['OverTime'] = X_train['OverTime'].map({'Yes': 1, 'No': 0})
X_test['OverTime'] = X_test['OverTime'].map({'Yes': 1, 'No': 0})

#Check value counts
X_train['OverTime'].value_counts()
X_test['OverTime'].value_counts()



0    217
1     77
Name: OverTime, dtype: int64

In [10]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_train_scaled = scaler.fit_transform(X_train)

# Scale the training and testing data
X_test_scaled = scaler.transform(X_test)


In [11]:
# Create a OneHotEncoder for the Department column
from sklearn.preprocessing import OneHotEncoder

encoder_department = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
# Create two new variables by applying the encoder
# to the training and testing data
y_train_department_encoded = encoder_department.fit_transform(y_train[['Department']])
y_test_department_encoded = encoder_department.transform(y_test[['Department']])

In [12]:
# Create a OneHotEncoder for the Attrition column
encoder_attrition = OneHotEncoder(sparse_output=False)

In [13]:
# Fit the encoder to the training data
# Create two new variables by applying the encoder to the training and testing data
y_train_attrition_encoded = encoder_attrition.fit_transform(y_train[['Attrition']])
y_test_attrition_encoded = encoder_attrition.transform(y_test[['Attrition']])

# Print the shape of the encoded data to verify
print("Shape of y_train_department_encoded:", y_train_department_encoded.shape)
print(np.array(y_train_department_encoded))

print("Shape of y_train_attrition_encoded:", y_train_attrition_encoded.shape)
print(np.array(y_train_attrition_encoded))

Shape of y_train_department_encoded: (1176, 3)
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape of y_train_attrition_encoded: (1176, 2)
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]


## Part 2: Create, Compile, and Train the Model

In [14]:
from tensorflow.keras.layers import Input, Dense

In [15]:
# Find the number of columns in the X training data
num_col = X_train_scaled.shape[1]
print("Number of columns in X training data:", num_col)

# Create the input layer
input_layer = Input(shape=(num_col,))

# Create at least two shared layers
shared_layer1 = layers.Dense(64, activation='relu')(input_layer)
shared_layer2 = layers.Dense(32, activation='relu')(shared_layer1)

Number of columns in X training data: 17


In [16]:
# Create a branch for Department with a hidden layer and an output layer

# Create the hidden layer
department_hidden = Dense(16, activation='relu')(shared_layer2)

# Create the output layer
department_output = Dense(
    y_train_department_encoded.shape[1], 
    activation='softmax', name='department_output')(department_hidden)

# Create a branch for Attrition with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden = layers.Dense(
    16, activation='relu')(shared_layer2)

# Create the output layer
attrition_output = layers.Dense(
    y_train_attrition_encoded.shape[1], 
    activation='sigmoid', name='attrition_output')(attrition_hidden)

# Create the model
model = Model(inputs=input_layer, outputs=[department_output, attrition_output])

# Compile the model
model.compile(optimizer='adam',
              loss={'department_output': 'categorical_crossentropy',
                    'attrition_output': 'binary_crossentropy'},
              metrics={'department_output': 'accuracy',
                       'attrition_output': 'accuracy'})

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 17)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 64)        │      1,152 │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 32)        │      2,080 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 16)        │        528 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 16)        │        528 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_output   │ (None, 3)         │         51 │ dense_2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output    │ (None, 2)         │         34 │ dense_3[0][0]     │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 4,373 (17.08 KB)

 Trainable params: 4,373 (17.08 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
# Train the model
history = model.fit(X_train_scaled, 
                    [y_train_department_encoded, y_train_attrition_encoded],
                    epochs=100,
                    batch_size=32,
                    validation_split=0.2,
                    verbose=1)


Epoch 1/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - attrition_output_accuracy: 0.3834 - attrition_output_loss: 0.7744 - department_output_accuracy: 0.2086 - department_output_loss: 0.7110 - loss: 1.4857 - val_attrition_output_accuracy: 0.8008 - val_attrition_output_loss: 0.5389 - val_department_output_accuracy: 0.5678 - val_department_output_loss: 0.6514 - val_loss: 1.1915
Epoch 2/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - attrition_output_accuracy: 0.8368 - attrition_output_loss: 0.4917 - department_output_accuracy: 0.6226 - department_output_loss: 0.6301 - loss: 1.1220 - val_attrition_output_accuracy: 0.7966 - val_attrition_output_loss: 0.4621 - val_department_output_accuracy: 0.6314 - val_department_output_loss: 0.5784 - val_loss: 1.0504
Epoch 3/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - attrition_output_accuracy: 0.8334 - attrition_output_loss: 0.4221 - department_output_accuracy: 0.6607 - department_output_loss: 0.5471 - loss: 0.9697 - val_attrition_output_accuracy: 0.7966 - 

In [18]:
# Evaluate the model with the testing data
evaluation = model.evaluate(X_test_scaled, 
                            [y_test_department_encoded, y_test_attrition_encoded], return_dict=True)




10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step - attrition_output_accuracy: 0.8256 - attrition_output_loss: 1.0314 - department_output_accuracy: 0.5612 - department_output_loss: 0.9951 - loss: 2.0477


In [19]:
print(evaluation)

{'attrition_output_accuracy': 0.8299319744110107, 'attrition_output_loss': 1.0353758335113525, 'department_output_accuracy': 0.5782312750816345, 'department_output_loss': 0.8733744621276855, 'loss': 2.0254125595092773}


In [20]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {evaluation['department_output_accuracy']* 100:.2f}%")
print(f"Attrition Accuracy: {evaluation['attrition_output_accuracy'] * 100:.2f}%")

# Print the loss for both department and attrition
print(f"Department Loss: {evaluation['department_output_loss']:.4f}")
print(f"Attrition Loss: {evaluation['attrition_output_loss']:.4f}")

# Print the overall loss
print(f"Overall Loss: {evaluation['loss']:.4f}")

Department Accuracy: 57.82%
Attrition Accuracy: 82.99%
Department Loss: 0.8734
Attrition Loss: 1.0354
Overall Loss: 2.0254


## Summary

### 1. Is accuracy the best metric to use on this data? Why or why not?

### Accuracy might not be the best metric to use on this data, especially if the classes are imbalanced. In such cases, metrics like precision, recall, or F1-score could provide more insight into the model's performance.

### 2. What activation functions did you choose for your output layers, and why?

### For the department output layer, I chose the softmax activation function because it is suitable for multi-class classification problems. For the attrition output layer, I used the sigmoid activation function as it is appropriate for binary classification tasks.

### 3. Can you name a few ways that this model might be improved?

### The model might be improved by:
### - Tuning hyperparameters such as learning rate, batch size, and number of epochs.
### - Using more advanced architectures or adding more layers to the neural network.
### - Implementing regularization techniques like dropout to prevent overfitting.
### - Collecting more data or performing data augmentation to increase the dataset size.